# image:
#   file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
    export FLASK_APP=jogoteca
    export FLASK_ENV=development
  init: |
    python3 -m venv venv
    . venv/bin/activate
  command: |
    pip install Flask
    python jogoteca.py
vscode:
  extensions:
    - ms-python.python
